/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#5c2400",
        "inverse-primary": "#80d5cb",
        "tertiary-container": "#5f6a7f",
        "surface-container": "#eeeeed",
        outline: "#6e7977",
        "surface-bright": "#f9f9f8",
        primary: "#005c55",
        surface: "#f9f9f8",
        "on-background": "#1a1c1c",
        error: "#ba1a1a",
        "surface-container-low": "#f3f4f3",
        "on-error": "#ffffff",
        "surface-container-high": "#e8e8e7",
        "primary-container": "#0f766e",
        "tertiary-fixed": "#d8e3fb",
        "on-error-container": "#93000a",
        "surface-dim": "#dadad9",
        "secondary-container": "#fd761a",
        "outline-variant": "#bdc9c6",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#111c2d",
        "on-primary-container": "#a3faef",
        "on-surface": "#1a1c1c",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#3c475a",
        "on-secondary-fixed-variant": "#783200",
        "on-primary-fixed-variant": "#00504a",
        "primary-fixed-dim": "#80d5cb",
        "on-primary-fixed": "#00201d",
        "inverse-surface": "#2f3130",
        "secondary-fixed-dim": "#ffb690",
        "on-secondary": "#ffffff",
        secondary: "#9d4300",
        "on-secondary-fixed": "#341100",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#e2ebff",
        background: "#f9f9f8",
        "inverse-on-surface": "#f1f1f0",
        "surface-variant": "#e2e2e2",
        "primary-fixed": "#9cf2e8",
        "secondary-fixed": "#ffdbca",
        tertiary: "#475266",
        "surface-tint": "#006a63",
        "on-surface-variant": "#3e4947",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "tertiary-fixed-dim": "#bcc7de",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        gutter: "24px",
        "margin-mobile": "16px",
        base: "4px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
